Rscript --vanilla 2_fit_mcmc.R --init "results/vb_extra/stayhome/rand_lag/fit.rds" --dir "mcmc_extra/stayhome/rand_lag" --intervention stayhome --no_temporal  --warmup 400 --iter 1200 --thin 8 --nchains 4
Rscript --vanilla 2_fit_mcmc.R --init "results/vb_extra/decrease/rand_lag/fit.rds" --dir "mcmc_extra/decrease/rand_lag" --intervention decrease --no_temporal --warmup 400 --iter 1200 --thin 8 --nchains 4
Rscript --vanilla 2_fit_mcmc.R --init "results/vb_extra/stayhome/bent_cable/fit.rds" --dir "mcmc_extra/stayhome/bent_cable" --intervention stayhome --no_temporal --warmup 400 --iter 1200 --thin 8 --nchains 4
Rscript --vanilla 2_fit_mcmc.R --init "results/vb_extra/decrease/bent_cable/fit.rds" --dir "mcmc_extra/decrease/bent_cable" --intervention decrease --no_temporal --warmup 400 --iter 1200 --thin 8 --nchains 4
Rscript --vanilla 2_fit_mcmc.R --init "results/vb_extra/stayhome/bent_cable/fit.rds" --dir "mcmc_extra/stayhome/bent_cable" --intervention stayhome --autocor 0.5 --ar_scale 0.1 --thin 8 --warmup 400 --iter 1200 --nchains 4
Rscript --vanilla 2_fit_mcmc.R --init "results/vb_extra/decrease/bent_cable/fit.rds" --dir "mcmc_extra/decrease/bent_cable" --intervention decrease --autocor 0.5 --ar_scale 0.1 --warmup 400 --iter 1200 --thin 8 --nchains 4
Rscript --vanilla 2_fit_mcmc.R --init "results/vb_extra/stayhome/no_ny_no_temporal/fit.rds" --dir "mcmc_extra/stayhome/no_ny_no_temporal" --exclude_ny --intervention stayhome --no_temporal --warmup 400 --iter 1200 --thin 8 --nchains 4
Rscript --vanilla 2_fit_mcmc.R --init "results/vb_extra/decrease/no_ny_no_temporal/fit.rds" --dir "mcmc_extra/decrease/no_ny_no_temporal" --exclude_ny --intervention decrease --no_temporal --warmup 400 --iter 1200 --thin 8 --nchains 4
Rscript --vanilla 2_fit_mcmc.R --init "results/vb_extra/stayhome/no_cities_temporal/fit.rds" --dir "mcmc_extra/stayhome/no_cities_temporal" --exclude_cities_post_inter --intervention stayhome --no_temporal --warmup 400 --iter 1200 --thin 8 --nchains 4
Rscript --vanilla 2_fit_mcmc.R --init "results/vb_extra/decrease/no_cities_temporal/fit.rds" --dir "mcmc_extra/decrease/no_cities_temporal" --exclude_cities_post_inter --intervention decrease --no_temporal --warmup 400 --iter 1200 --thin 8 --nchains 4
