
```{r}
library(tidyverse)
library(magrittr)
library(feather)
library(gridExtra)
library(cowplot)
```

```{r}
up = 10
down = -10

gg_days_btwn_sampling <- function(data, name, up, down, lag_decrease = NULL, lag = NULL) {
  p <- data %>% 
    ggplot() + 
    geom_point(aes(x=date, y=y)) + 
    geom_line(aes(x=date, y=fit_med), 
              col = "#0072B2", size = 1) + 
    geom_ribbon(aes(x=date, ymin=fit_lo, ymax=fit_hi), 
                alpha= 0.1, fill = "#0072B2") + 
      geom_line(aes(x=date, y=ctr1_med), 
              col = "#D55E00", size = 1) + 
      geom_ribbon(aes(x=date, ymin=ctr1_lo, ymax=ctr1_hi), 
                alpha= 0.1, fill = "#D55E00") + 
       geom_line(aes(x=date, y=ctr3_med), 
              col = "#009E73", size = 1) + 
      geom_ribbon(aes(x=date, ymin=ctr3_lo, ymax=ctr3_hi), 
                alpha= 0.1, fill = "#009E73") +  
      labs(title = name, x = "", y = "") + 
      xlim(as.Date("2020-03-01"), as.Date("2020-04-30"))
    
    if(!is.null(lag_decrease)) {
      p <- p + 
      geom_vline(aes(xintercept = decrease_50_total_visiting), color = "#0072B2") + 
      geom_vline(aes(xintercept = decrease_50_total_visiting + lag_decrease), linetype="dotted", color = "#0072B2") + 
      geom_vline(aes(xintercept = decrease_50_total_visiting + lag_decrease + down), linetype="dotted", color = "#009E73") + 
      geom_vline(aes(xintercept = decrease_50_total_visiting + lag_decrease + up), linetype="dotted", color = "#D55E00")
    }
    
    if(!is.null(lag)) {
      p <- p + 
      geom_vline(aes(xintercept = stayhome), color = "#0072B2") + 
      geom_vline(aes(xintercept = stayhome + lag), linetype="dotted", color = "#0072B2") + 
      geom_vline(aes(xintercept = stayhome + lag + down), linetype="dotted", color = "#009E73") + 
      geom_vline(aes(xintercept = stayhome + lag + up), linetype="dotted", color = "#D55E00")
    }

  p + theme_minimal_grid()
}
```

```{r}
county_stayhome <- read_feather("../data/county_train_stayhome.feather")
county_fit <- readRDS("./stay_home/county_fit.rds")
county_ctr1 <- readRDS("./stay_home/county_ctr1.rds")
county_ctr3 <- readRDS("./stay_home/county_ctr3.rds")

## obtain distribution values from fit sampling
county_stayhome %<>% 
  mutate(
    fit_mu = apply(county_fit, 2, mean),
    fit_med = apply(county_fit, 2, quantile, probs = 0.5), # use posterior median to hand skewness
    fit_lo = apply(county_fit, 2, quantile, probs = 0.05),
    fit_hi = apply(county_fit, 2, quantile, probs = 0.95))

county_stayhome %<>% 
  mutate(
    ctr1_mu = apply(county_ctr1, 2, mean),
    ctr1_med = apply(county_ctr1, 2, quantile, probs = 0.5), # use posterior median to hand skewness
    ctr1_lo = apply(county_ctr1, 2, quantile, probs = 0.05),
    ctr1_hi = apply(county_ctr1, 2, quantile, probs = 0.95),
    ctr3_mu = apply(county_ctr3, 2, mean),
    ctr3_med = apply(county_ctr3, 2, quantile, probs = 0.5), # use posterior median to hand skewness
    ctr3_lo = apply(county_ctr3, 2, quantile, probs = 0.05),
    ctr3_hi = apply(county_ctr3, 2, quantile, probs = 0.95))
```

```{r}
county_decrease <- read_feather("../data/county_train_decrease.feather")
county_fit <- readRDS("./mobility_decrease/county_fit.rds")
county_ctr1 <- readRDS("./mobility_decrease/county_ctr1.rds")
county_ctr3 <- readRDS("./mobility_decrease/county_ctr3.rds")

## obtain distribution values from fit sampling
county_decrease %<>% 
  mutate(
    fit_mu = apply(county_fit, 2, mean),
    fit_med = apply(county_fit, 2, quantile, probs = 0.5), # use posterior median to hand skewness
    fit_lo = apply(county_fit, 2, quantile, probs = 0.05),
    fit_hi = apply(county_fit, 2, quantile, probs = 0.95))

county_decrease %<>% 
  mutate(
    ctr1_mu = apply(county_ctr1, 2, mean),
    ctr1_med = apply(county_ctr1, 2, quantile, probs = 0.5), # use posterior median to hand skewness
    ctr1_lo = apply(county_ctr1, 2, quantile, probs = 0.05),
    ctr1_hi = apply(county_ctr1, 2, quantile, probs = 0.95),
    ctr3_mu = apply(county_ctr3, 2, mean),
    ctr3_med = apply(county_ctr3, 2, quantile, probs = 0.5), # use posterior median to hand skewness
    ctr3_lo = apply(county_ctr3, 2, quantile, probs = 0.05),
    ctr3_hi = apply(county_ctr3, 2, quantile, probs = 0.95))
```


```{r}
fips_ <- c(53033, 36047, 22051)
name_ <- county_stayhome %>%
      filter(fips %in% fips_) %>% 
      distinct(fips, state, county) %>%
      mutate(name = paste(state, county, sep = ", "))
```

```{r}
x = 53033

p1a <- county_stayhome %>% 
  filter(fips == x) %>% 
  gg_days_btwn_sampling(name = name_$name[name_$fips == x], 
                        up = up, 
                        down = down, 
                        lag = 12) + 
  ylim(c(0,50)) + 
  labs(subtitle = "Policy-intervention")

p1b <- county_decrease %>% 
  filter(fips == x) %>% 
  gg_days_btwn_sampling(name = "", 
                        up = up, 
                        down = down, 
                        lag_decrease = 12) + 
  ylim(c(0,50)) + 
  theme(axis.text.y =  element_blank()) + 
  labs(subtitle = "Mobility-intervention")

prow1 <- plot_grid(p1a, p1b, scale = 0.95)
prow1
```

```{r}
x = 36047

p2a <- county_stayhome %>% 
  filter(fips == x) %>% 
  gg_days_btwn_sampling(name = "New York, Kings County", 
                        up = up, 
                        down = down, 
                        lag = 12) + 
  ylim(c(0,500))

p2b <- county_decrease %>% 
  filter(fips == x) %>% 
  gg_days_btwn_sampling(name = "", 
                        up = up, 
                        down = down, 
                        lag_decrease = 12) + 
  ylim(c(0,500)) + 
  theme(axis.text.y =  element_blank())

prow2 <- plot_grid(p2a, p2b, scale = 0.95)
prow2
```

```{r}
x = 22051

p3a <- county_stayhome %>% 
  filter(fips == x) %>% 
  gg_days_btwn_sampling(name = name_$name[name_$fips == x], 
                        up = up, 
                        down = down, 
                        lag = 12) + 
  ylim(c(0,50))

p3b <- county_decrease %>% 
  filter(fips == x) %>% 
  gg_days_btwn_sampling(name = "", 
                        up = up, 
                        down = down, 
                        lag_decrease = 12) + 
  ylim(c(0,50))  + 
  theme(axis.text.y =  element_blank())

prow3 <- plot_grid(p3a, p3b, scale = 0.95)
prow3
```

```{r}
plot_grid(prow1, prow2, prow3, nrow = 3, rel_heights = c(1.2,1,1))
ggsave("../images/six_panel.pdf", width = 7, height = 6)
```




